ENV_VARS=$(cat .vercel/.env.preview.local)
DATABASE_URL_KEY=DATABASE_URL_4719c80b6fe911b091a7c05124
DB_REGEX="$DATABASE_URL_KEY=\"([^\"]*)\""

if [[ $ENV_VARS =~ $DB_REGEX ]]; then
EXISTING_URL=$(echo ${BASH_REMATCH[1]})
echo $EXISTING_URL 
# EXISTING_URL="${EXISTING_URL//$'\n'/''}"
echo $EXISTING_URL
EXISTING_URL=$(echo $EXISTING_URL | base64)
echo $EXISTING_URL
EXISTING_URL="${EXISTING_URL//$'\n'/''}"
echo $EXISTING_URL

# echo "URL=$EXISTING_URL" >> $GITHUB_OUTPUT
fi