name: Code Check

on:
  pull_request:

env:
  SKIP_ENV_VALIDATION: true

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Check lint
        run: pnpm lint

      - name: Check TypeScript
        run: pnpm type-check

      - name: Run tests
        run: pnpm test

      - name: Check TypeScript
        run: pnpm build
