name: Clear Preview Deployment

on:
  pull_request:
    types:
      - closed

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

permissions:
  pull-requests: write
  issues: write

jobs:
  preview-hash:
    name: Generate preview hash
    uses: ./.github/workflows/preview-hash.yml

  remove-database:
    name: Remove database
    runs-on: ubuntu-latest
    needs:
      - preview-hash
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Delete database
        run: flyctl apps destroy ${{ needs.preview-hash.outputs.PREVIEW_SHA }} --yes || true

  remove-database-environment:
    name: Remove database env
    runs-on: ubuntu-latest
    needs:
      - preview-hash
    steps:
      - uses: actions/checkout@v3
      - run: vercel env rm DATABASE_URL_${{ needs.preview-hash.outputs.PREVIEW_SHA }} --yes --token=${{ secrets.VERCEL_TOKEN }} || true

  remove-preview-environment:
    name: Remove preview environment
    runs-on: ubuntu-latest
    needs:
      - preview-hash
    steps:
      - name: Get preview URL
        id: preview-url
        run: |
          ALIASES=$(vercel alias ls --token=${{ secrets.VERCEL_TOKEN }})         
          URL=$(echo "$ALIASES" | grep "${{ needs.preview-hash.outputs.hash }}.*" | awk '{print $1}')

          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Remove previous preview environment
        if: steps.preview-url.outputs.url
        run: vercel remove ${{ steps.preview-url.outputs.url }} --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Find preview deployment comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: preview-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: <!-- __PREVIEW_DEPLOYMENT__ -->

      - name: Create or update preview link comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.preview-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## ❌ Your preview environment was removed!
            <!-- __PREVIEW_DEPLOYMENT__ -->
