name: Preview hash

on:
  workflow_call:
    outputs:
      hash:
        value: ${{ jobs.generate-hash.outputs.hash }}
      database-url-key:
        value: ${{ jobs.compose-database-key.outputs.key }}

jobs:
  generate-hash:
    name: Generate hash
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.generate-hash.outputs.hash }}
    steps:
      - id: generate-hash
        name: Generate hash from branch name
        run: |
          SHA=$(echo "${{ github.head_ref }}" | sha256sum | cut -c5-30)
          echo "hash=$SHA" >> $GITHUB_OUTPUT

  compose-database-key:
    name: Compose database key
    runs-on: ubuntu-latest
    needs:
      - generate-hash
    outputs:
      key: ${{ steps.compose-key.outputs.key }}
    steps:
      - name: Compose database key
        id: compose-key
        run: |
          DATABASE_URL_KEY=DATABASE_URL_${{ needs.generate-hash.outputs.hash }}
          echo "key=$DATABASE_URL_KEY" >> $GITHUB_OUTPUT
