name: Assign preview domain

on:
  workflow_call:
    inputs:
      preview-url:
        type: string
        required: true

jobs:
  preview-hash:
    name: Generate preview hash
    uses: ./.github/workflows/preview-hash.yml

  current-preview-url:
    name: Get current preview URL
    runs-on: ubuntu-latest
    needs:
      - preview-hash
    outputs:
      url: ${{ steps.current-alias.outputs.url}}
    steps:
      - name: Get current alias
        id: current-alias
        run: |
          ALIASES=$(vercel alias ls --token=${{ secrets.VERCEL_TOKEN }})         
          URL=$(echo "$ALIASES" | grep "${{ needs.preview-hash.outputs.hash }}.*" | awk '{print $1}')

          echo "url=$URL" >> $GITHUB_OUTPUT

  alias-preview:
    name: Assign preview domain
    runs-on: ubuntu-latest
    needs:
      - preview-hash
      - current-preview-url
    steps:
      - name: Alias current deployment
        run: |
          vercel alias \
            ${{ inputs.preview-url }} \
            ${{ needs.preview-hash.outputs.hash }}.vercel.app \
            --token=${{ secrets.VERCEL_TOKEN }}

  destroy-previous-preview:
    name: Destroy previous preview
    runs-on: ubuntu-latest
    needs:
      - alias-preview
      - current-preview-url
    if: needs.current-preview-url.outputs.url
    steps:
      - name: Remove previous preview environment
        run: vercel remove ${{ needs.current-preview-url.outputs.url }} --yes --token=${{ secrets.VERCEL_TOKEN }}
