name: Clear Preview Deployment

on:
  pull_request:
    types:
      - closed

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

permissions:
  pull-requests: write
  issues: write

jobs:
  remove-database:
    name: Remove preview database
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Generate Branch Preview URL
        id: generate-preview-url
        run: |
          BRANCH_SHA=$(echo ${{ steps.extract_branch.outputs.branch }} | sha256sum | cut -c5-38)
          echo "preview-sha=$BRANCH_SHA" >> $GITHUB_OUTPUT

      - name: Delete database
        run: flyctl apps destroy ${{ steps.generate-preview-url.outputs.preview-sha }} --yes

  remove-preview:
    name: Remove preview environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find first vercel preview comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: preview-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: <!-- __PREVIEW_DEPLOYMENT__ -->

      - name: Get current preview environment url
        id: vercel-preview-url
        run: |
          REGEX="(<!-- __VERCEL_PREVIEW_URL: )(.*)( -->)"
          COMMENT_BODY="${{ steps.preview-comment.outputs.comment-body }}"

          if [[ "$COMMENT_BODY" =~ $REGEX ]]; then
              echo "VERCEL_PREVIEW_URL=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          else
              echo "No previous Preview Environment. SKip!"
          fi

      - name: Remove previous preview environment
        run: |
          VERCEL_PREVIEW_URL="${{ steps.vercel-preview-url.outputs.VERCEL_PREVIEW_URL }}"

          if [ $VERCEL_PREVIEW_URL ]; then
              vercel remove $VERCEL_PREVIEW_URL --yes --token=${{ secrets.VERCEL_TOKEN }}
          else
              echo "No previous Preview Environment"
          fi

      - name: Create or update preview link comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.preview-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## ❌ Your preview environment was removed!
            <!-- __PREVIEW_DEPLOYMENT__ -->
