name: Clear Preview Deployment

on:
  pull_request:
    types:
      - closed

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

permissions:
  pull-requests: write
  issues: write

jobs:
  generate-preview-hash:
    name: Generate preview URL
    runs-on: ubuntu-latest
    outputs:
      PREVIEW_SHA: ${{ steps.generate-preview-hash.outputs.PREVIEW_SHA }}
    steps:
      - name: Generate Branch Preview URL
        id: generate-preview-hash
        run: |
          BRANCH_SHA=$(echo ${{ github.head_ref }} | sha256sum | cut -c5-30)
          echo "PREVIEW_SHA=$BRANCH_SHA" >> $GITHUB_OUTPUT

  remove-database:
    name: Remove preview database
    runs-on: ubuntu-latest
    needs:
      - generate-preview-hash
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Delete database
        run: flyctl apps destroy ${{ needs.generate-preview-hash.outputs.PREVIEW_SHA }} --yes

  clear-preview-env:
    name: Remove database ENV
    runs-on: ubuntu-latest
    needs:
      - generate-preview-hash
    steps:
      - uses: actions/checkout@v3
      - run: vercel env rm DATABASE_URL_${{ needs.generate-preview-hash.outputs.PREVIEW_SHA }} --yes --token=${{ secrets.VERCEL_TOKEN }} || true

  remove-preview:
    name: Remove preview environment
    runs-on: ubuntu-latest
    needs:
      - generate-preview-hash
    steps:
      - name: Find preview deployment comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: preview-comment
        with:
          issue-number: ${{ github.event.number }}
          body-includes: <!-- __PREVIEW_DEPLOYMENT__ -->

      - name: Get current preview url
        id: preview-url
        run: |
          REGEX="__PREVIEW_URL: (.*) -->"
          COMMENT_BODY="${{ steps.preview-comment.outputs.comment-body }}"

          if [[ "$COMMENT_BODY" =~ $REGEX ]]; then
              echo "URL=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

      - name: Destroy previous preview
        run: |
          PREVIEW_URL="${{ steps.preview-url.outputs.URL }}"

          if [ $PREVIEW_URL ]; then
              vercel remove $PREVIEW_URL --yes --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Create or update preview link comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.preview-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            ## ❌ Your preview environment was removed!
            <!-- __PREVIEW_DEPLOYMENT__ -->
